name: MACARON All-in-One Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8+
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk iproute2 net-tools wireless-tools
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run syntax checks
      run: |
        python -m py_compile main.py
        python -c "import main; print('✅ main.py imports successfully')"
        
    - name: Run comprehensive tests
      run: |
        python test_all_in_one.py
        
    - name: Test installer syntax
      run: |
        bash -n install_all_in_one.sh
        echo "✅ Installer script syntax OK"

  compatibility-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        pip install -r requirements.txt
        
    - name: Test import compatibility
      run: |
        python -c "import main; print(f'✅ Python {python_version} compatibility OK')" python_version="${{ matrix.python-version }}" 